name: Bygg og deploy

on: [push]

env:
    docker_image: ghcr.io/${{ github.repository }}/rekrutteringsbistand-container:${{ github.sha }}

jobs:
    bygg-og-push-docker-image:
        name: Bygg og push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      server/package-lock.json
            - name: Installer avhengigheter
              run: npm ci
            - name: Bygg applikasjon
              run: npm run build
            - name: Test applikasjon
              run: npm run test
            - name: Installer avhengigheter for server
              run: cd server && npm ci
            - name: Bygg server
              run: cd server && npm run build
            - name: Bygg og publiser Docker-image
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker build --tag ${IMAGE} .
                  echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
                  docker push ${IMAGE}

    deploy-til-dev:
        name: Deploy til dev-gcp
        needs: bygg-og-push-docker-image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/proxy-til-kandidatsok-es'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: deploy/nais-dev.yaml

    deploy-to-prod:
        name: Deploy til prod-gcp
        needs: deploy-til-dev
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: deploy/nais-prod.yaml
